version: '2.2'

services:

  my-app:
    container_name: clinicPlus-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'