version: "3.3"
services:
  app:
    build:
      args:
        user: icare
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: icare
    container_name: icare-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - icare

  db:
    image: mysql:5.7
    container_name: icare-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - icare

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: icare-phpmyadmin
    restart: always
    environment:
      PMA_HOST: icare-db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8002:80"

  nginx:
    image: nginx:alpine
    container_name: icare-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - icare

networks:
  icare:
    driver: bridge
